spring:
  data:
    mongodb:
      uri: mongodb+srv://sushantgupta4u_db_user:1qV1QVNhml2Ly4vf@cluster0.vjm3aus.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true
      allow-circular-references: true

  redis:
    host: redis-15257.crce217.ap-south-1-1.ec2.cloud.redislabs.com
    port: 15257
    password: lMh3m9waDfXTFmiVs2OjUElvdgw1FJqH
   # url: redis://default:lMh3m9waDfXTFmiVs2OjUElvdgw1FJqH@redis-15257.crce217.ap-south-1-1.ec2.cloud.redislabs.com:15257
#    host: localhost
#    port: 6379



  mail:
    host: smtp.gmail.com
    port: 587
    username: sushantgupta4u@gmail.com
    password: keyrjkltejnvtwsp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  





weather:
  api:
    key: 1f92c99c850e2f2dda04eeaddc9846ec

server:
  port: 8081
  servlet:
    context-path: /journal