spring:
  profiles:
    active: prod

logging:
  level:
    net:
      engineeringdigest:
        journalApp: DEBUG


#logging:
#  level:
#    net:
#      engineeringdigest:
#        journalApp:
#          service:
#            UserService: OFF


#logging:
#  level:
#    root:ERROR

#root: OFF


